import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Injectable } from '@angular/core';import { environment } from '@env/environment';import { ApiResponse } from '@models/application';import { CashflowPaged, Expense, MonthlyFinancialReport, RecoverableValue, Supplier } from '@models/cashflow';import { Observable } from 'rxjs';
@Injectable({providedIn:'root'}) export class CashflowService {private readonly base=`${environment.api}/admin/finance`;constructor(private readonly http:HttpClient){}
 private params(filters:any):HttpParams{let p=new HttpParams();Object.entries(filters||{}).forEach(([k,v])=>{if(v!==''&&v!==null&&v!==undefined)p=p.set(k,String(v));});return p;}
 suppliers(filters:any):Observable<ApiResponse<CashflowPaged<Supplier>>>{return this.http.get<ApiResponse<CashflowPaged<Supplier>>>(`${this.base}/suppliers`,{params:this.params(filters)});} saveSupplier(value:any,id?:number):Observable<ApiResponse<Supplier>>{return id?this.http.patch<ApiResponse<Supplier>>(`${this.base}/suppliers/${id}`,value):this.http.post<ApiResponse<Supplier>>(`${this.base}/suppliers`,value);}
 expenses(filters:any):Observable<ApiResponse<CashflowPaged<Expense>>>{return this.http.get<ApiResponse<CashflowPaged<Expense>>>(`${this.base}/expenses`,{params:this.params(filters)});} saveExpense(value:any,id?:number):Observable<ApiResponse<Expense>>{return id?this.http.patch<ApiResponse<Expense>>(`${this.base}/expenses/${id}`,value):this.http.post<ApiResponse<Expense>>(`${this.base}/expenses`,value);} payExpense(id:number,value:any):Observable<ApiResponse<Expense>>{return this.http.patch<ApiResponse<Expense>>(`${this.base}/expenses/${id}/mark-as-paid`,value);}
 recoverables(filters:any):Observable<ApiResponse<CashflowPaged<RecoverableValue>>>{return this.http.get<ApiResponse<CashflowPaged<RecoverableValue>>>(`${this.base}/recoverables`,{params:this.params(filters)});} saveRecoverable(value:any,id?:number):Observable<ApiResponse<RecoverableValue>>{return id?this.http.patch<ApiResponse<RecoverableValue>>(`${this.base}/recoverables/${id}`,value):this.http.post<ApiResponse<RecoverableValue>>(`${this.base}/recoverables`,value);} resolveRecoverable(id:number,type:'received'|'lost',value:any):Observable<ApiResponse<RecoverableValue>>{return this.http.patch<ApiResponse<RecoverableValue>>(`${this.base}/recoverables/${id}/mark-as-${type}`,value);}
 exportMonthly(month:string,format:'pdf'|'docx'):Observable<HttpResponse<Blob>>{return this.http.get(`${this.base}/reports/monthly/export`,{params:{month,format},observe:'response',responseType:'blob'});}
 monthly(month:string):Observable<ApiResponse<MonthlyFinancialReport>>{return this.http.get<ApiResponse<MonthlyFinancialReport>>(`${this.base}/reports/monthly`,{params:{month}});} history(page:number,per_page:number):Observable<ApiResponse<CashflowPaged<MonthlyFinancialReport>>>{return this.http.get<ApiResponse<CashflowPaged<MonthlyFinancialReport>>>(`${this.base}/reports/monthly/history`,{params:{page,per_page}});}}
